# Your Solution
version: '3.8'

services:
  book_catalog:
    image: projectpart5.azurecr.io/book_catalog:latest
    container_name: book_catalog
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://sit722_part5_f0o4_user:ZhgHzEj2BKzfucE59SD6SsUPILyK6j5D@dpg-crpus9rv2p9s738crb70-a.oregon-postgres.render.com/sit722_part5_f0o4

  inventory_management:
    image: projectpart5.azurecr.io/inventory_management:latest
    container_name: inventory_management
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://sit722_part5_f0o4_user:ZhgHzEj2BKzfucE59SD6SsUPILyK6j5D@dpg-crpus9rv2p9s738crb70-a.oregon-postgres.render.com/sit722_part5_f0o4