services:
  postgres:
    image: postgres:13
    container_name: postgres_part5
    environment:
      POSTGRES_USER: sit722_part5_f0o4_user
      POSTGRES_PASSWORD: ZhgHzEj2BKzfucE59SD6SsUPILyK6j5D
      POSTGRES_DB: sit722_part5_f0o4
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
  book_catalog:
    build: ./book_catalog
    container_name: book_catalog_part4
    environment:
      DATABASE_URL: "postgresql://sit722_part5_f0o4_user:ZhgHzEj2BKzfucE59SD6SsUPILyK6j5D@dpg-crpus9rv2p9s738crb70-a.oregon-postgres.render.com/sit722_part5_f0o4"
    ports:
      - "8002:8000"
    depends_on:
      - postgres
 
  inventory_management:
    build: ./inventory_management
    container_name: inventory_management_part4
    environment:
      DATABASE_URL: "postgresql://sit722_part5_f0o4_user:ZhgHzEj2BKzfucE59SD6SsUPILyK6j5D@dpg-crpus9rv2p9s738crb70-a.oregon-postgres.render.com/sit722_part5_f0o4"
    ports:
      - "8003:8001"
    depends_on:
      - postgres
volumes:
  postgres_data:
